 
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxWrapper from "./redux/ReduxWrapper";
import BeautifulSidebar from "./components/Siderbar/Siderbar";
import { SidebarProvider } from "@/components/ui/sidebar";
import Navbar from "./components/Navbar/Navbar";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxWrapper>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body  suppressHydrationWarning>
          <div className="flex h-screen overflow-hidden bg-background">
            <SidebarProvider>
              <BeautifulSidebar />
              <div className="flex flex-1 flex-col">
                <Navbar />
                <main className="flex-1  overflow-auto p-6">{children}</main>
                <Toaster />
              </div>
            </SidebarProvider>
          </div>
        </body>
      </html>
    </ReduxWrapper>
  );
}
